import Head from "next/head";
import styles from "../styles/Home.module.scss";
import banner from "../assets/images/banner.png";
import Image from "next/legacy/image";
import Movies from "../component/Movies";
import { Pagination } from "@mui/material";

export default function Home({ data }) {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main__img}>
        <Image src={banner} alt={"banner"} layout="responsive"  priority />
      </div>
      <div className={styles.container__movies__wrapper}> 
        <span className={styles.popular_movies}>Trending</span>
        <div className={styles.movie__card__wrapper}>
        {data.results.slice(0,16).map((movie,index) => (
          <div className={styles.movie__card} key={index}>
            <Movies movie={movie} key={index} />
          </div>
        ))}
        </div>
        <div className={styles.pagination}>
        <Pagination count={10} />
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps({ req, res }) {
  const response = await fetch(
    `https://api.themoviedb.org/3/trending/movie/day?api_key=6e37d364da090a453e6c12697bcfcde7&page=1`
  );
  const result = await response.json();
  return {
    props: {
      data: result,
    },
  };
}
